- project/MicroService.scala
i.e. scala files under the it/ directory
> [FD][AOSS-1435] Enable automatic header creation for integration tests

- app/uk/gov/hmrc/agentclientauthorisation/controllers/AuthorisationRequestController.scala
- app/uk/gov/hmrc/agentclientauthorisation/model/AgentClientAuthorisationRequest.scala
- app/uk/gov/hmrc/agentclientauthorisation/repository/AuthorisationRequestRepository.scala
- it/uk/gov/hmrc/agentclientauthorisation/AgentClientAuthorisationISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/sa/AuthorisationRequestMongoRepositoryISpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/controllers/AuthorisationRequestControllerSpec.scala
Please merge at the same time as https://github.com/hmrc/agent-client-authorisation-frontend/pull/16
> [FD][AOSS-1424] Rename request field clientSaUtr to clientRegimeId in the API

- it/uk/gov/hmrc/agentclientauthorisation/AgentClientAuthorisationISpec.scala
...by passing regime when creating requests.
> [FD][AOSS-1424] Fix test

- README.md
- it/uk/gov/hmrc/agentclientauthorisation/AgentClientAuthorisationISpec.scala
Also add a test for the self link. Didn't add tests for the
accept/reject/cancel links because they aren't implemented yet.
Changed test to make failure stack traces easier to read by narrowing
the scope of the eventually.
> [FD] README.md: Make request JSON HAL compatible

- app/uk/gov/hmrc/agentclientauthorisation/controllers/AuthorisationRequestController.scala
- app/uk/gov/hmrc/agentclientauthorisation/model/AgentClientAuthorisationRequest.scala
- app/uk/gov/hmrc/agentclientauthorisation/sa/controllers/SaLookupController.scala
- app/uk/gov/hmrc/agentclientauthorisation/sa/services/SaLookupService.scala
- test/uk/gov/hmrc/agentclientauthorisation/controllers/AuthorisationRequestControllerSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/sa/services/SaLookupServiceSpec.scala
- Interface is smaller and more consistent
- Business desicions are moved to the caller (matching of postcodes)
- Moved functions that belong to the SaService into the service itself
> [BL] Small code improvements in the SaLookupService and it's usage

- app/uk/gov/hmrc/agentclientauthorisation/controllers/InvitationsController.scala
...to bring error responses closer to the conditions that trigger them.
> [FD][APB-5] Refactor

- agent-client-authorisation.raml
- conf/app.routes
- conf/application.conf
- conf/definition.routes
- conf/prod.routes
- public/api/definition.json
- public/api/documentation/0.95a/Agency-Cancel-invitation.xml
- public/api/documentation/0.95a/Agency-Create-an-invitation.xml
- public/api/documentation/0.95a/Agency-Sent-invitation.xml
- public/api/documentation/0.95a/Agency-Sent-invitations.xml
- public/api/documentation/0.95a/foo.json
- raml/atoms.raml
- raml/invitation_example.json
- raml/invitations.raml
- raml/invitations_example.json
I've updated the RAML and modularised it (with more examples). So far only the agencies and clients are defined in the RAML but only agencies in XML.
> Apb63 merge branch

- app/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/InvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsService.scala
- conf/app.routes
- it/uk/gov/hmrc/agentclientauthorisation/AgentClientAuthorisationISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/ClientInvitationsISpec.scala
Refactoring as mentioned on Friday.
> Separate client api

- it/uk/gov/hmrc/agentclientauthorisation/AgencyInvitationsISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/ClientInvitationsISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyInvitesClientISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/NoInvitationsISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/package.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/AuthStubs.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/RandomArn.scala
- resources/public/api/conf/0.95a/application.raml
> [BL][APB-282] Adding dsl driven set of scenarios to test the features

- app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsHal.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsHal.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxAgencyInvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxClientInvitationsController.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxAgencyInvitationsISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxClientInvitationsISpec.scala
See discussion at https://github.com/hmrc/agent-client-authorisation/pull/59#discussion_r87767776
> APB-74 Share HAL/JSON generation code between production and sandbox controllers

- it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyFiltersByClientIdAndStatusISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyFiltersByRegime.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyInvitesClientISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/ClientFiltersByStatusISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/AgencyApi.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/ClientApi.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/ScenarioHelpers.scala
Scenarios 4, 5(partial) and 6.
> Apb 282 contract tests

- conf/app.routes
- it/uk/gov/hmrc/agentclientauthorisation/AgencyInvitationsISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/ClientInvitationsISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyFiltersByClientIdAndStatusISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyFiltersByRegime.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyInvitesClientISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/scenarios/ClientFiltersByStatusISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/AgencyApi.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/ClientApi.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/ScenarioHelpers.scala
> Rename create url

- app/uk/gov/hmrc/agentclientauthorisation/service/PostcodeService.scala
- it/uk/gov/hmrc/agentclientauthorisation/AgencyInvitationsISpec.scala
[APB-593][LA,SD] Add test for DES to return 404. Fix defect to return ClientRegistrationNotFound.
> Apb 593 003

- conf/application.conf
- project/MicroServiceBuild.scala
caused by outdated play-hmrc-api library and wrong appUrl configuration
> [AO] fix deployment issue

- it/uk/gov/hmrc/agentclientauthorisation/support/Http.scala
This reverts commit 8387092e6ce68ad6f0a7bda1b39069815c69c992.
> Revert "[APB-368][FD] Remove unused imports" to fix it:compile

- app/uk/gov/hmrc/agentclientauthorisation/connectors/DesConnector.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/PostcodeService.scala
- it/uk/gov/hmrc/agentclientauthorisation/connectors/DesConnectorISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/DesStubs.scala
- test/uk/gov/hmrc/agentclientauthorisation/controllers/actions/AgentInvitationValidationSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/service/InvitationsServiceSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/service/PostcodeServiceSpec.scala
Please review but do not merge until fix to agent stubs is complete (ask one of the Pauls).
> [APB-1101][ph,pt] fix des bug

- app/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsRepository.scala
> [APB-1813][APB-1917][PT, AO]: Added Sparse Indexing

- app/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsRepository.scala
Reverts hmrc/agent-client-authorisation#143
> Revert "[APB-1813][APB-1917][PT, AO]: Override ensureIndexes and added logging."

- app/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsRepository.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsService.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsStatusUpdateScheduler.scala
- it/uk/gov/hmrc/agentclientauthorisation/service/InvitationsStatusUpdateSchedulerISpec.scala
This PR is to address some performance issues discovered in the staging environment. `AtomicUpdate` trait is already deprecated and should be removed from the codebase. More tests have to follow.
> [AO] performance fix

- app/uk/gov/hmrc/agentclientauthorisation/connectors/RelationshipsConnector.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsControllerISpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/model/InvitationSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/support/TestData.scala
- testcommon/uk/gov/hmrc/agentclientauthorisation/support/TestConstants.scala
- Added missing URN link to accept invitations
- More tests to be added with different scenarios after QA testing of this ticket.
> [APB-5070][LC]- Fixed-Urn-Url

- app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/PostcodeService.scala
- app/uk/gov/hmrc/agentclientauthorisation/util/FailedResultException.scala
- app/uk/gov/hmrc/agentclientauthorisation/util/util.scala
- test/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsControllerSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/service/PostcodeServiceSpec.scala
Just fixing the Future(None) = success, Future(Some) = failure, so that it uses success and fail more appropriately.
> Apb 5207 known fact update

- app/uk/gov/hmrc/agentclientauthorisation/connectors/CitizenDetailsConnector.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/ClientNameService.scala
- it/uk/gov/hmrc/agentclientauthorisation/connectors/CitizenDetailsConnectorISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/TerminateInvitationsISpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsControllerSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/service/ClientNameServiceSpec.scala
I've kept 403 for the failure responses, since this makes it a non-breaking change.
> [APB-5207][BS] Postcode from Citizen Details Service

- app/uk/gov/hmrc/agentclientauthorisation/service/EmailService.scala
The other piece of this is in the HMRC-EMAIL-RENDERER reop
> [APB-5227][BS] dynamic auth accepted email

- conf/messages
Checked `hmrc-email-renderer but there are no specific references that need changing.
> APB-5332 [CS] update service names

- app/uk/gov/hmrc/agentclientauthorisation/connectors/DesConnector.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/Cache.scala
- conf/app.routes
These changes are required to enable Plastic Packaging Tax in agent invitations.
> APB-5442 Add PPT functionality

- app/uk/gov/hmrc/agentclientauthorisation/connectors/AuthActions.scala
- build.sbt
- conf/application.conf
- it/uk/gov/hmrc/agentclientauthorisation/connectors/AuthActionsISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyAlternativeItsaControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyCheckKnownFactInvitationsControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentCancelInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentCreateInvitationISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentGetInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentGetTrustNameIFEnabledISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentGetTrustNameISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentReferenceControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentServicesControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/CgtSubscriptionISPec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/service/AgentCacheProviderImplISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/AppAndStubs.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/Http.scala
- project/plugins.sbt
- No functional changes in this PR
- Upgrades dependency versions
- Integration tests updated to send in "Authorization" header
> Dependency upgrades

- app/uk/gov/hmrc/agentclientauthorisation/config/AppConfig.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/BusinessNamesService.scala
- build.sbt
- conf/application.conf
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentServicesControllerISpec.scala
- Uses Guava RateLimiter to throttle calls to DES
- Catches all exceptions from DES call and returns default (blank) value for business name
> Rate limits batch of calls to fetch business names from DES

- app/uk/gov/hmrc/agentclientauthorisation/model/AgentDetailsDesResponse.scala
- it/uk/gov/hmrc/agentclientauthorisation/connectors/DesConnectorISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentServicesControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/DesStubs.scala
- test/uk/gov/hmrc/agentclientauthorisation/controllers/AgentReferenceControllerSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/service/AgentLinkServiceSpec.scala
For https://github.com/hmrc/agent-services-account-frontend/pull/378
> APB-7274 [CS] add agencyPhone to agency details

- app/uk/gov/hmrc/agentclientauthorisation/config/AppConfig.scala
- app/uk/gov/hmrc/agentclientauthorisation/connectors/DesIFConnector.scala
- app/uk/gov/hmrc/agentclientauthorisation/connectors/DesIfHeaders.scala
- app/uk/gov/hmrc/agentclientauthorisation/model/BusinessDetails.scala
- app/uk/gov/hmrc/agentclientauthorisation/model/MtdItIdIfResponse.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsService.scala
- conf/application.conf
- it/uk/gov/hmrc/agentclientauthorisation/connectors/DesConnectorISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/AgentServicesControllerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/DesStubs.scala
- move from DES to IF
- mtdbsa renamed to mtdId
- IF auth token added (TBC)
- remove duplicate stub mapping
> APB-7591[CS] update API#1171

- app/uk/gov/hmrc/agentclientauthorisation/connectors/DesConnector.scala
- app/uk/gov/hmrc/agentclientauthorisation/connectors/IfConnector.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsController.scala
- app/uk/gov/hmrc/agentclientauthorisation/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/ClientNameService.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsService.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/PostcodeService.scala
- it/uk/gov/hmrc/agentclientauthorisation/connectors/DesConnectorISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/connectors/IfConnectorEnabledISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/connectors/IfConnectorISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/controllers/TerminateInvitationsISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/service/InvitationsStatusUpdateSchedulerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/service/RoutineJobSchedulerISpec.scala
- it/uk/gov/hmrc/agentclientauthorisation/support/DesStubs.scala
- test/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsControllerSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/service/ClientNameServiceSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/service/PostcodeServiceSpec.scala
- test/uk/gov/hmrc/agentclientauthorisation/support/MocksWithCache.scala
+ split Des/If connector (took me a little longer than expected, sorry!)
> APB-7591[CS] update response schema

- app/uk/gov/hmrc/agentclientauthorisation/config/AppConfig.scala
- app/uk/gov/hmrc/agentclientauthorisation/connectors/DesConnector.scala
- app/uk/gov/hmrc/agentclientauthorisation/connectors/DesIfHeaders.scala
- app/uk/gov/hmrc/agentclientauthorisation/connectors/IfConnector.scala
- conf/application.conf
- test/uk/gov/hmrc/agentclientauthorisation/connectors/DesIfHeadersSpec.scala
Some further refactoring could be applied, e.g. moving Pillar2 to IF connector and streamlining the getHeaders function to cater to both a little better. This additional work was left out given wider refactoring efforts going on.
> [APB-7713][GW] add DES/IF headers based on the url host

- app/uk/gov/hmrc/agentclientauthorisation/service/ClientNameService.scala
- app/uk/gov/hmrc/agentclientauthorisation/service/EmailService.scala
- test/uk/gov/hmrc/agentclientauthorisation/service/ClientNameServiceSpec.scala
Updated the get client details code to include supporting agent
> [APB-8683] Updated the get client details code to include supporting agent
