hmrc/agent-client-authorisation

app/uk/gov/hmrc/agentclientauthorisation/microserviceWiring.scala

This will allow Splunk to be queried to find out what was sent to and returned by the APIs that we call (not services - service-to-service calls are excluded).

[FD][AOSS-1422] Enable WSHttp implicit auditing

---

app/uk/gov/hmrc/agentclientauthorisation/microserviceGlobal.scala
app/uk/gov/hmrc/agentclientauthorisation/microserviceWiring.scala
conf/application.conf
invitations.raml

Updated after discussion with @howzat and story refinement
- Postcode will be supplied as part of the invitation and must be checked against the customer's details
- We need to support CT as well as SA UTRs
- Added 403 where appropriate
- Removed 204 for empty list responses
- Change mtdArn -> arn, documentation should be sufficient to identify _which_ arn
- Replaced agentName/agencyName with arn

Apb 31 raml

---

README.md
app/uk/gov/hmrc/agentclientauthorisation/controllers/InvitationsController.scala
it/uk/gov/hmrc/agentclientauthorisation/AgentClientAuthorisationISpec.scala

See https://confluence.tools.tax.service.gov.uk/display/ApiPlatform/Error+Handling for API platform guidelines on error responses.

[FD][APB-5] Include explanatory body in error response for unsupported regime

---

app/uk/gov/hmrc/agentclientauthorisation/controllers/InvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/model/Invitation.scala
app/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsRepository.scala
app/uk/gov/hmrc/agentclientauthorisation/service/PostcodeService.scala
it/uk/gov/hmrc/agentclientauthorisation/AgentClientAuthorisationISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsMongoRepositoryISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/SecuredEndpointBehaviours.scala
it/uk/gov/hmrc/agentclientauthorisation/support/StubUtils.scala

User research as presented by Kate suggests that accountants and their clients use "Client" not "Customer" and that some clients object to "Customer".
This commit only addresses the code - https://github.com/hmrc/agent-client-authorisation/pull/28 addresses the docs.

[FD][APB-5] Terminology: "Client" instead of "Customer"

---

app/uk/gov/hmrc/agentclientauthorisation/UriPathEncoding.scala
test/uk/gov/hmrc/agentclientauthorisation/UriPathEncodingSpec.scala

This is to keep agent-client-authorisation in sync with the changes made in https://github.com/hmrc/agent-client-authorisation-frontend/pull/51

[FD][APB-150] encodePathSegments: include initial slash

---

app/uk/gov/hmrc/agentclientauthorisation/model/Invitation.scala
conf/app.routes
it/uk/gov/hmrc/agentclientauthorisation/AgencyInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/ClientInvitationsISpec.scala
test/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsControllerSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsControllerSpec.scala

Also change cancel URL and verb to match RAML.
Do not merge until after https://github.com/hmrc/agent-client-authorisation-frontend/tree/apb-336-accepting-hateoas to avoid breaking the frontend.

[FD,LA][APB-337] Remove invitation ID from API responses

---

conf/application-json-logger.xml

Note that app-config-prod/agent-client-authorisation.yaml has "logger.application: INFO" hence the <logger name="application" level="INFO"/> here.
https://hmrcdigital.slack.com/archives/event-play-upgrade/p1479317602001465
"play 2.5 does not respect the `logger.{logger root}: INFO` convention from application config used to override log levels and set them per environment
the only file that will currently define log levels in all environments is the `application-json-logger.xml` packaged with the application"

[FD][APB-343] Don't spam the production logs with INFO messages

---

conf/logback.xml

This makes it easier to see the test results when running `sbt test` or similar.

[FD] Turn down log levels on local machines

---

it/uk/gov/hmrc/agentclientauthorisation/support/AppAndStubs.scala

This allows multiple concurrent test runs (e.g. different branches in different directories) and reduces the risk of a port conflict on Jenkins.

[FD] Use a random port for the test server

---

resources/public/api/definition.json

This limits access to the application *and its documentation* to whitelisted applications.
See https://<confluence>/display/DTRG/Restricting+APIs+to+Private+Access+on+the+API+Platform
Currently whitelisted applications:
- API platform "Mandatory applications to whitelist" (see above confluence page) for all environments
- "Agents Test" applications in QA and Production
This is just a quick initial version - we should probably make the whitelist configurable as described on the confluence page.

[FD][APB-386] Make API private

---

it/uk/gov/hmrc/agentclientauthorisation/AgencyInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/ClientInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxClientInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyFiltersByRegimeISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/APIRequests.scala
it/uk/gov/hmrc/agentclientauthorisation/support/AgencyApi.scala
it/uk/gov/hmrc/agentclientauthorisation/support/AppAndStubs.scala
it/uk/gov/hmrc/agentclientauthorisation/support/ClientApi.scala
it/uk/gov/hmrc/agentclientauthorisation/support/ScenarioHelpers.scala
it/uk/gov/hmrc/agentclientauthorisation/support/SecuredEndpointBehaviours.scala
it/uk/gov/hmrc/agentclientauthorisation/support/halTestHelpers.scala
test/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsControllerSpec.scala

Added a test to filter by client ID
Added an APIRequest trait to allow resource paths to be in one place
Moved older *ISpec tests to use new idioms

APB 282 Contract Tests

---

app/uk/gov/hmrc/agentclientauthorisation/ApiPlatformRequestHandler.scala
conf/app.routes
conf/application.conf
conf/prod.routes
conf/sandbox.routes
it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxAgencyInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxClientInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/APIRequests.scala

i.e. accept sandbox requests without the /agent-client-authorisation path prefix because the API platform strips this context from the path when making requests to the backend service.

[FD][APB-431] Make sandbox routes accessible via the API platform

---

app/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/HardCodedSandboxIds.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxAgencyInvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxClientInvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxRootController.scala
it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxAgencyInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxClientInvitationsISpec.scala

The sandbox uses a test user that doesn't pass the security checks, so without this change the routes always returned a 401 when called in sandbox mode.
Because we aren't checking whether the user is a SA client or agent we can't use obtain the current user's identifiers any more and instead have to use hardcoded IDs when the response contains an identifier for the logged in user.

[FD][APB-431] Remove security checks from sandbox routes

---

app/uk/gov/hmrc/agentclientauthorisation/ApiPlatformRequestHandler.scala
it/uk/gov/hmrc/agentclientauthorisation/AgencyInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/ClientInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/APIRequests.scala

i.e. accept sandbox requests without the /agent-client-authorisation path prefix because the API platform strips this context from the path when making requests to the backend service.

[FD][APB-434] Make non-sandbox routes accessible via the API platform

---

app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsHal.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsHal.scala
app/uk/gov/hmrc/agentclientauthorisation/views/definition.scala.txt
it/uk/gov/hmrc/agentclientauthorisation/controllers/api/ApiPlatformISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxAgencyInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/halTestHelpers.scala
resources/public/api/conf/0.0/examples/get-agency-invitations-sent-example.json
resources/public/api/conf/0.0/examples/get-client-invitations-received-example.json
resources/public/api/conf/0.0/schemas/invitations.json

Conceptually the links are links to the embedded resources, so the _links entry and the _embedded entries should have the same name.

[FD] Rename "invitation" link to "invitations" and use a consistent name for the API

---

project/MicroService.scala

...so that we don't need to pass the port when using "sbt run"

[FD] Add default port to sbt settings

---

app/uk/gov/hmrc/agentclientauthorisation/audit/AuditService.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsController.scala
test/uk/gov/hmrc/agentclientauthorisation/audit/AuditSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsControllerSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/support/ClientEndpointBehaviours.scala

which has been moved to agent-invitations-frontend

[APB-797][RV,AO] remove audit event AgentClientInvitationResponse

---

app/uk/gov/hmrc/agentclientauthorisation/audit/AuditService.scala
app/uk/gov/hmrc/agentclientauthorisation/connectors/AuthConnector.scala
app/uk/gov/hmrc/agentclientauthorisation/connectors/RelationshipsConnector.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/BaseClientInvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsHal.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/MtdItClientInvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/NiClientInvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxAgencyInvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/model/Invitation.scala
app/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsRepository.scala
app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsService.scala
it/uk/gov/hmrc/agentclientauthorisation/controllers/sandbox/SandboxAgencyInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsMongoRepositoryISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/scenarios/AgencyFilteringByClientIdIApiPlatformISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/ApiRequests.scala
it/uk/gov/hmrc/agentclientauthorisation/support/ClientApi.scala
it/uk/gov/hmrc/agentclientauthorisation/support/ScenarioHelpers.scala
it/uk/gov/hmrc/agentclientauthorisation/support/StubUtils.scala
test/uk/gov/hmrc/agentclientauthorisation/audit/AuditSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/connectors/AuthConnectorSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsControllerSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/controllers/MtdItClientInvitationsControllerSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/model/InvitationSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/service/InvitationsServiceSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/support/ClientEndpointBehaviours.scala
test/uk/gov/hmrc/agentclientauthorisation/support/TestData.scala
testcommon/uk/gov/hmrc/agentclientauthorisation/support/TestConstants.scala

These changes also include the use of ClientId on the Invitation  model replacing the raw String types, this was introduced now rather than in 1831 (when ClientId was introduced) as it required implementing a custom Json.Format for persistence which was also required to ensure we default to a sensible value for any old records that don't have a expiryDate.

Apb 1865 - Add 'use by' date to 'invitation complete' page

---

build.sbt
conf/application.conf
it/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsMongoRepositoryISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/repository/MongoAgentReferenceRepositoryISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/repository/ScheduleRepositoryISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/AppAndStubs.scala
it/uk/gov/hmrc/agentclientauthorisation/support/MongoApp.scala

This PR aims to fix the random "No primary node is available" problems occurring on the local environment when running tests or service. We define now the failover strategy, previously missing.

[APB-3376][AO] define failoverStrategy for mongodb connector, upgrade simple-reactivemongo to 7.12.0

---

app/uk/gov/hmrc/agentclientauthorisation/model/Invitation.scala
app/uk/gov/hmrc/agentclientauthorisation/repository/InvitationRecordFormat.scala
app/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsRepository.scala
app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsService.scala
it/uk/gov/hmrc/agentclientauthorisation/repository/InvitationsMongoRepositoryISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/TestDataSupport.scala
test/uk/gov/hmrc/agentclientauthorisation/support/TestData.scala

Add isRelationshipEnded flag to mongo invitation record. This is to enable us to decide whether or not to display the 'Cancel Authorisation' button on the track page - an ideal solution would've been for us to introduce a new InvitationStatus, however that would have affected all of our third party stakeholders. Also amended InvitationsService.changeInvitationStatus to facilitate the request - this may not make perfect sense as the InvitationStatus doesn't actually get updated, it remains as Accepted, instead the isRelationshipEnded flag gets set to true.

[APB-4475][JR]

---

app/uk/gov/hmrc/agentclientauthorisation/audit/AuditService.scala
app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsService.scala
it/uk/gov/hmrc/agentclientauthorisation/controllers/TerminateInvitationsISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/service/InvitationsStatusUpdateSchedulerISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/service/RoutineJobSchedulerISpec.scala
testcommon/uk/gov/hmrc/agentclientauthorisation/support/TestConstants.scala

- When an invitation request with status `Partialauth` has expired, send an audit event `HmrcExpiredAgentServiceAuthorisation`. These will be picked up via the `RoutineJobScheduler`
- Some refactoring of `RoutineJobSchedulerISpec`:
- use a longer default patience (via `IntegrationPatience`) to allow enough time for the next scheduled job to get picked up in order to get a successful test result.
- Separate out each test case scenario for clarity.

APB-5327 new audit event for when a Partialauth invitation expires

---

app/uk/gov/hmrc/agentclientauthorisation/connectors/EisConnector.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsController.scala
test/uk/gov/hmrc/agentclientauthorisation/model/SimpleCbcSubscriptionSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/service/ClientNameServiceSpec.scala

It’s not 100% clear from the spec if primary and secondary contacts are both required fields.
So far I’ve treated both as required, but we could run into issues down the line if only the primary contact is mandatory.
Also for the known fact check - are we happy if they match either contact email, or should it only be the primary contact?

APB-7216 [CS] fix cbc subscription reads

---

app/uk/gov/hmrc/agentclientauthorisation/connectors/AuthActions.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/AgencyInvitationsController.scala
app/uk/gov/hmrc/agentclientauthorisation/controllers/ClientStatusController.scala
app/uk/gov/hmrc/agentclientauthorisation/model/Invitation.scala
conf/app.routes

Should allow uk cbc clients to view their invitation.
There's still might be some extra changes while I'm looking at agent-client-authorisation.

APB-7216 [CS] support client auth for uk cbc

---

app/uk/gov/hmrc/agentclientauthorisation/service/EmailService.scala
conf/application-json-logger.xml
it/uk/gov/hmrc/agentclientauthorisation/controllers/ClientInvitationsControllerISpec.scala
it/uk/gov/hmrc/agentclientauthorisation/support/EmailStub.scala
project/AppDependencies.scala

add back messages wrapper that was removed in June. As a result, emails were being sent without service descriptions.

add back messages wrapper to email information

---

app/uk/gov/hmrc/agentclientauthorisation/controllers/AgentReferenceController.scala
app/uk/gov/hmrc/agentclientauthorisation/model/Invitation.scala
app/uk/gov/hmrc/agentclientauthorisation/model/InvitationInfo.scala
app/uk/gov/hmrc/agentclientauthorisation/service/InvitationsService.scala
it/test/uk/gov/hmrc/agentclientauthorisation/controllers/AgentReferenceControllerISpec.scala
test/uk/gov/hmrc/agentclientauthorisation/controllers/AgentReferenceControllerSpec.scala
test/uk/gov/hmrc/agentclientauthorisation/service/InvitationsServiceSpec.scala

An update to the functionality was agreed with @geoffreywatson - the updateAltItsa side effect has been removed from this endpoint rather than wire up the same effects in ACR - it is now a pure listing method - we have agreed updates to altItsa statuses can happen on the agent's side of things as and when an agent attempts to sign up the client

APB-9113 use flag to get from ACR
